name: "Build and release"

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: "ubuntu-latest"
    permissions:
      issues: write
      contents: write
      pull-requests: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Latest release-replace plugin fails https://github.com/jpoehnelt/semantic-release-replace-plugin/issues/223
          dry_run: true
          extra_plugins: |
            @semantic-release/git
            @semantic-release/github
            semantic-release-replace-plugin@1.2.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cargo-edit
      - run: cargo set-version ${{ steps.semantic.outputs.new_release_version }}
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: Cargo
          path: |
            Cargo.lock
            Cargo.toml
  build:
    needs: [prepare]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # don't fail other jobs if one fails
      matrix:
        build: [x86_64-linux, aarch64-linux, x86_64-macos, x86_64-windows]
        include:
        - build: x86_64-linux
          os: ubuntu-20.04
          rust: stable
          target: x86_64-unknown-linux-gnu
          cross: false
        - build: aarch64-linux
          os: ubuntu-20.04
          rust: stable
          target: aarch64-unknown-linux-gnu
          cross: true
        - build: x86_64-macos
          os: macos-latest
          rust: stable
          target: x86_64-apple-darwin
          cross: false
        - build: aarch64-macos
          os: macos-latest
          rust: stable
          target: aarch64-apple-darwin
          cross: false
        - build: x86_64-windows
          os: windows-2019
          rust: stable
          target: x86_64-pc-windows-msvc
          cross: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Cargo
        shell: bash
        run: |
          mv -f Cargo/* ./
      - name: Install ${{ matrix.rust }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release --locked --bins --target ${{ matrix.target }}
      - name: Build archive
        shell: bash
        run: |
          mkdir dist
          BIN_NAME=project-tree-manager
          if [ "${{ matrix.os }}" = "windows-2019" ]; then
            cp "target/${{ matrix.target }}/release/$BIN_NAME.exe" "dist/"
          else
            cp "target/${{ matrix.target }}/release/$BIN_NAME" "dist/"
          fi
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: bin-${{ matrix.build }}
          path: dist

  release:
    runs-on: "ubuntu-latest"
    needs: [build]
    permissions:
      issues: write
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Prepare release
        run: |
          ./scripts/release.sh
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Latest release-replace plugin fails https://github.com/jpoehnelt/semantic-release-replace-plugin/issues/223
          extra_plugins: |
            @semantic-release/git
            @semantic-release/github
            semantic-release-replace-plugin@1.2.0
