name: "Build and release"

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: "ubuntu-latest"
    permissions:
      issues: write
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      - name: "Build & release"
        run: |
          ./release.sh
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extends: |
            @google/semantic-release-replace-plugin
